modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = "https://github.com/matthewperiut/clay-soldiers/"
license = "MIT"

[[mods]]
modId = "clay"
version = "${version}"
displayName = "Clay Soldiers"
authors = "Slainlite"
description = '''
This adds clay soldiers that attack for you!
'''
#logoFile = "icon.png"

[[dependencies.clay]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clay]]
modId = "geckolib"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "NONE"
side = "BOTH"
